theme: jekyll-theme-hacker
title: Ermanno Goletto on GitHubx
logo: http://www.devadmin.it/wp-content/uploads/2017/02/DevAdmin2-Trasparent-135-MVPHorizontal.png
show_downloads: false
is_project_page: false
